# Generated by Django 5.2.5 on 2025-08-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
    ]
