# Generated by Django 5.2.5 on 2025-08-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='membership_date',
            new_name='membership',
        ),
    ]
